from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('', views.home, name="home"),
    path('loai/<int:loai_id>/', views.home, name="loai"),
    path('chitietsp/<int:sanpham_id>/', views.chitietsp, name="chitiet"),
    path('dangnhap/', views.dangnhap, name="dangnhap"),
    path('dangky/', views.dangky, name="dangky"),
    path('kichhoat/<uidb64>/<token>/', views.kichhoat, name='kichhoat'),
    
    # Quên mật khẩu
    path('quen-mat-khau/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        form_class=views.CustomPasswordResetForm
    ), name='password_reset'),
    path('quen-mat-khau/da-gui/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('dat-lai-mat-khau/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('dat-lai-mat-khau/hoan-tat/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('tai-khoan/', views.thongtintaikhoan, name='thongtintaikhoan'),
    path('dangxuat/', auth_views.LogoutView.as_view(next_page='home'), name="dangxuat"),
    path('themgiohang/<int:sanpham_id>/', views.themgiohang, name="themgiohang"),
    path('suagiohang/<int:sanpham_id>/', views.suagiohang, name="suagiohang"),
    path('xoagiohang/<int:sanpham_id>/', views.xoagiohang, name="xoagiohang"),
    path('giohang/', views.giohang, name="giohang"),
    path('thanhtoan/', views.thanhtoan, name="thanhtoan"),
    path('camon/', views.thanhtoan, name="camon"),
    path('don-hang-cua-toi/', views.donhangcuatoi, name='donhangcuatoi'),
    path('don-hang-cua-toi/<int:donhang_id>/', views.chitietdonhang_khach, name='chitietdonhang_khach'),
    path('quantri/', views.quantri, name="quantri"),
    path('quantri/sanpham/', views.quanlysanpham, name="quanlysanpham"),
    path('quantri/sanpham/xoa/<int:sanpham_id>/', views.xoasanpham, name="xoasanpham"),
    path('quantri/sanpham/sua/<int:sanpham_id>/', views.suasanpham, name="suasanpham"),
    path('quantri/sanpham/them/', views.themsanpham, name="themsanpham"),
    path('quantri/kho/lichsu/', views.lichsukho, name="lichsukho"),
    path('quantri/donhang/', views.quanlydonhang, name="quanlydonhang"),
    path('quantri/donhang/<int:donhang_id>/', views.duyetdonhang, name="duyetdonhang"),
    path('quantri/donhang/chitietdonhang/<int:donhang_id>/', views.chitietdonhang, name="chitietdonhang"),
    path('quantri/donhang/xoa/<int:donhang_id>/', views.xoadonhang, name="xoadonhang"),
    path('quantri/loai/', views.quanlyloai, name="quanlyloai"),
    path('quantri/loai/them/', views.themloai, name="themloai"),
    path('quantri/loai/xoa/<int:loai_id>/', views.xoaloai, name="xoaloai"),
    path('quantri/loai/sua/<int:loai_id>/', views.sualoai, name="sualoai"),
    path('search/', views.timkiem, name="timkiem"),
    path('quantri/cuahang/', views.quanlycuahang, name="quanlycuahang"),
    path('quantri/cuahang/them/', views.themcuahang, name="themcuahang"),
    path('quantri/cuahang/sua/<int:cuahang_id>/', views.suacuahang, name="suacuahang"),
    path('quantri/cuahang/xoa/<int:cuahang_id>/', views.xoacuahang, name="xoacuahang"),
    path('quantri/taikhoan/', views.quanlytaikhoan, name="quanlytaikhoan"),
    path('quantri/taikhoan/capnhat/<int:user_id>/', views.capnhatquyen, name="capnhatquyen"),
    path('map/', views.map_view, name="map"),
    path('xoataikhoan/<int:id>/', views.xoataikhoan, name='xoataikhoan'),
    path('send-mailtrap/', views.send_mailtrap, name='send_mailtrap'),
    path('gioi-thieu/', views.gioithieu, name='gioithieu'),
    path('chinh-sach-bao-hanh/', views.chinhsachbaohanh, name='chinhsachbaohanh'),
    path('chinh-sach-doi-tra/', views.chinhsachdoitra, name='chinhsachdoitra'),
    path('dieu-khoan-su-dung/', views.dieukhoansudung, name='dieukhoansudung'),
    path('export-inventory-template/', views.export_inventory_template, name='export_inventory_template'),
    path('import-inventory-excel/', views.import_inventory_excel, name='import_inventory_excel'),
    path('export-lichsu-kho/', views.export_lichsukho_excel, name='export_lichsukho_excel'),
    path('quantri/about/', views.admin_about, name='admin_about'),
    path('gioithieu/', views.gioithieu, name='about'),
]
