# Generated by Django 6.0.1 on 2026-03-05 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CUAHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('diachi', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LOAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DONHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=11)),
                ('diachi', models.TextField()),
                ('tongtien', models.IntegerField()),
                ('ngaydat', models.DateTimeField(auto_now_add=True)),
                ('trangthai', models.IntegerField(default=1)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('khachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GIOHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khachhang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SANPHAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('gia', models.IntegerField()),
                ('hinh', models.ImageField(blank=True, null=True, upload_to='')),
                ('soluong', models.IntegerField(default=0)),
                ('loaisp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.loai')),
            ],
        ),
        migrations.CreateModel(
            name='CHITIETGIOHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(default=1)),
                ('giohang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.giohang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='CHITIETDONHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField()),
                ('dongia', models.IntegerField()),
                ('donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.donhang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
            ],
        ),
    ]
