# Generated by Django 6.0.1 on 2026-03-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuahang',
            name='hinh',
            field=models.ImageField(blank=True, null=True, upload_to='cuahang/'),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
