# Generated by Django 6.0.1 on 2026-03-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cuahang_hinh_cuahang_is_open_cuahang_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuahang',
            name='is_open',
        ),
        migrations.AddField(
            model_name='cuahang',
            name='gio_dong',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='gio_mo',
            field=models.TimeField(default='08:00'),
        ),
    ]
