# Generated by Django 6.0.1 on 2026-03-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_cuahang_is_open_cuahang_gio_dong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuahang',
            name='rating',
        ),
    ]
