# Generated by Django 6.0.1 on 2026-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_cuahang_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='home.size'),
        ),
    ]
