# Generated by Django 6.0.1 on 2026-03-28 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_size_sanpham_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='size',
            name='ten',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='SANPHAM_SIZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(default=0)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.size')),
            ],
        ),
    ]
