# Generated by Django 6.0.1 on 2026-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_sanpham_sizes_alter_size_ten_sanpham_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='ten',
            field=models.CharField(max_length=10),
        ),
    ]
