# Generated by Django 6.0.1 on 2026-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_size_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='size',
            field=models.CharField(default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='chitietgiohang',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=2),
        ),
        migrations.DeleteModel(
            name='SANPHAM_SIZE',
        ),
        migrations.DeleteModel(
            name='SIZE',
        ),
    ]
