# Generated by Django 6.0.1 on 2026-03-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_chitietdonhang_size_chitietgiohang_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIZE_SANPHAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=2)),
                ('soluong', models.IntegerField(default=0)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='home.sanpham')),
            ],
        ),
    ]
