# Generated by Django 6.0.1 on 2026-03-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_size_sanpham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='home.sanpham'),
        ),
    ]
