# Generated by Django 6.0.1 on 2026-03-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_chitietdonhang_sanpham'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham'),
        ),
        migrations.CreateModel(
            name='TAIKHOAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taikhoan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SIZE_SANPHAM',
        ),
    ]
