# Generated by Django 6.0.1 on 2026-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_chitietdonhang_sanpham_taikhoan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('quanly', 'Quản lý'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
