# Generated by Django 6.0.1 on 2026-03-30 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_taikhoan_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HINHANH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh', models.ImageField(blank=True, null=True, upload_to='')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinhanh', to='home.sanpham')),
            ],
        ),
    ]
