# Generated by Django 6.0.1 on 2026-04-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='mota',
            field=models.TextField(blank=True, default=''),
        ),
    ]
