# Generated by Django 6.0.1 on 2026-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sanpham_mota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuahang',
            name='sodienthoai',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
