# Generated by Django 6.0.1 on 2026-04-19 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cuahang_sodienthoai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('quanly', 'Quản lý'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='LICHSUKHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2)),
                ('loai_biendong', models.CharField(choices=[('nhap', 'Nhap kho'), ('xuat', 'Xuat kho'), ('dieuchinh_tang', 'Dieu chinh tang'), ('dieuchinh_giam', 'Dieu chinh giam')], max_length=20)),
                ('soluong_thaydoi', models.IntegerField()),
                ('ton_truoc', models.IntegerField(default=0)),
                ('ton_sau', models.IntegerField(default=0)),
                ('ghichu', models.CharField(blank=True, default='', max_length=255)),
                ('thoigian', models.DateTimeField(auto_now_add=True)),
                ('nguoithuchien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichsu_kho', to='home.sanpham')),
            ],
            options={
                'ordering': ['-thoigian', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TONKHOSIZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2)),
                ('soluong', models.IntegerField(default=0)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonkho_sizes', to='home.sanpham')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sanpham', 'size'), name='uniq_tonkho_sanpham_size'), models.CheckConstraint(condition=models.Q(('soluong__gte', 0)), name='tonkho_size_non_negative')],
            },
        ),
    ]
