# Generated by Codex on 2026-04-19

from django.db import migrations
from django.db.models import Sum


def seed_tonkho_size(apps, schema_editor):
    SanPham = apps.get_model('home', 'SANPHAM')
    TonKhoSize = apps.get_model('home', 'TONKHOSIZE')

    size_order = ['S', 'M', 'L', 'XL']

    for sp in SanPham.objects.all().iterator():
        existing = {row.size: row for row in TonKhoSize.objects.filter(sanpham=sp)}

        if not existing:
            TonKhoSize.objects.bulk_create([
                TonKhoSize(sanpham=sp, size='S', soluong=0),
                TonKhoSize(sanpham=sp, size='M', soluong=max(sp.soluong, 0)),
                TonKhoSize(sanpham=sp, size='L', soluong=0),
                TonKhoSize(sanpham=sp, size='XL', soluong=0),
            ])
        else:
            for size in size_order:
                if size not in existing:
                    TonKhoSize.objects.create(sanpham=sp, size=size, soluong=0)

        tong = TonKhoSize.objects.filter(sanpham=sp).aggregate(total=Sum('soluong'))['total'] or 0
        if sp.soluong != tong:
            sp.soluong = tong
            sp.save(update_fields=['soluong'])


def noop_reverse(apps, schema_editor):
    # Keep stock data when rolling back code-level migrations.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_chitietdonhang_size_alter_taikhoan_role_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tonkho_size, reverse_code=noop_reverse),
    ]
