# Generated by Django 6.0.1 on 2026-04-20 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_seed_tonkho_size_from_sanpham'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tonkhosize',
            name='uniq_tonkho_sanpham_size',
        ),
        migrations.AddField(
            model_name='donhang',
            name='cuahang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cuahang'),
        ),
        migrations.AddField(
            model_name='lichsukho',
            name='cuahang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cuahang'),
        ),
        migrations.AddField(
            model_name='tonkhosize',
            name='cuahang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tonkho_sanpham', to='home.cuahang'),
        ),
        migrations.AlterField(
            model_name='lichsukho',
            name='loai_biendong',
            field=models.CharField(choices=[('nhap', 'Nhap kho'), ('xuat', 'Xuat kho'), ('dieuchinh_tang', 'Dieu chinh tang'), ('dieuchinh_giam', 'Dieu chinh giam')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tonkhosize',
            constraint=models.UniqueConstraint(fields=('sanpham', 'size', 'cuahang'), name='uniq_tonkho_sanpham_size_cuahang'),
        ),
    ]
