# Generated by Django 6.0.1 on 2026-02-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SANPHAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('gia', models.IntegerField()),
                ('mota', models.TextField()),
                ('hinh', models.ImageField(upload_to='hinh/')),
                ('soluong', models.IntegerField(default=0)),
                ('loaisp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.loai')),
            ],
        ),
    ]
